In [39]:
from tensorflow import keras

In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib

matplotlib.rcParams['axes.unicode_minus'] = False
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = '10'

In [41]:
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()

In [42]:
# 표준화작업
train_scaled = train_input/255.0
# train_scaled = train_scaled.reshape(-1,28*28)  # flatten층에서 사이즈 그대로 적용 28*28(배열화)
train_scaled.shape

(60000, 28, 28)

In [43]:
train_scaled, val_scaled, train_target, val_target = train_test_split(
    train_scaled, train_target, test_size=0.2, random_state=42
)

In [44]:
model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28)))
model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dropout(0.3))  # 30%를 제외시키는 규제적용
model.add(keras.layers.Dense(10,activation='softmax'))

In [45]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_4 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 100)            │        78,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 79,510 (310.59 KB)

 Trainable params: 79,510 (310.59 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.load_weights('model0529.weights.h5')

In [47]:
model.predict(val_scaled)

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step


array([[0.16227213, 0.07314967, 0.2085958 , ..., 0.13651228, 0.08130747,
        0.1404383 ],
       [0.07388297, 0.0611541 , 0.3152961 , ..., 0.07344382, 0.15802294,
        0.13591073],
       [0.11950978, 0.06657553, 0.09108869, ..., 0.19785939, 0.10610925,
        0.14103   ],
       ...,
       [0.09367213, 0.05498467, 0.19759338, ..., 0.07848503, 0.13313666,
        0.21210545],
       [0.17520525, 0.09004685, 0.20217364, ..., 0.09891041, 0.11118273,
        0.08498939],
       [0.07705607, 0.03142456, 0.20121966, ..., 0.1385208 , 0.17398635,
        0.05752999]], dtype=float32)

In [48]:
val_scaled

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.00784314, 0.        , 0.43921569, ..., 0.        ,
         0.        , 0.00392157],
        [0.00784314, 0.        , 0.08235294, ..., 0.        ,
         0.00392157, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 

In [49]:
val_target

array([8, 8, 7, ..., 8, 8, 1], dtype=uint8)

In [50]:
val_labels = np.argmax(model.predict(val_scaled),axis=1)
np.mean(val_labels == val_target)

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step


0.16983333333333334

In [51]:
val_labels

array([2, 2, 7, ..., 9, 2, 2], dtype=int64)

In [52]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# epochs 돌 때마다 loss, accuracy값을 저장
# train_scaled, val_scaled 함께 훈련시킴
history = model.fit(train_scaled, train_target,epochs=20, 
                    validation_data=(val_scaled,val_target))

Epoch 1/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7439 - loss: 0.7496 - val_accuracy: 0.8389 - val_loss: 0.4514
Epoch 2/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8337 - loss: 0.4604 - val_accuracy: 0.8629 - val_loss: 0.3817
Epoch 3/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8494 - loss: 0.4090 - val_accuracy: 0.8600 - val_loss: 0.3830
Epoch 4/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8611 - loss: 0.3763 - val_accuracy: 0.8681 - val_loss: 0.3697
Epoch 5/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8632 - loss: 0.3691 - val_accuracy: 0.8714 - val_loss: 0.3521
Epoch 6/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8723 - loss: 0.3508 - val_accuracy: 0.8775 - val_loss: 0.3353
Epoch 7/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8758 - loss: 0.3367 - val_accuracy: 0.8781 - val_loss: 0.3307
Epoch 8/20
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8753 - loss: 0.3381 - 