### 단층 퍼셉트론
    - 퍼셉트론 : 다수의 신호를 입력받아 하나의 신호를 출력
    - 입력신호(x1,x2), 출력신호(y1,y2), 가중치(w1,w2)로 구성
    - 가중합(weighted sum)이 임계치를 넘어야 출력

In [2]:
import numpy as np
x = np.array([0,1])
w = np.array([0.5,0.5])
b = -.7

np.sum(w*x)+b

-0.19999999999999996

### 활성화함수 (Activation Function)
    - sigmoid
    - ReLU
    - 비선형성 생성

In [3]:
# custom - 계산을 안정적으로 처리

def sigmoid(x):  # boolean 타입으로 return
    pos_mask = (x>=0)
    neg_mask = (x<0)
    z = np.zeros_like(x) # 입력값과 같은 크기의 배열을 0으로 생성
    z[pos_mask] = np.exp(-x[pos_mask]) # 지수함수
    z[neg_mask] = np.exp(x[neg_mask])
    top = np.ones_like(x)
    top[neg_mask] = z[neg_mask] # 입력 값이 0보다 작은 경우 분자를 exp(x)설정
    return top / (1+z)

# 1/1+exp(-x) # x가 무한하게 커지면 값이 1에 가까워지는데 연산하는데 메모리가 터지는 경우가 생김

In [4]:
# ReLU

def relu(x):
    return np.maximum(0,x)

In [5]:
x = np.array([-1., 1., 3.])
sigmoid(x)

array([0.26894142, 0.73105858, 0.95257413])

In [6]:
relu(x)

array([0., 1., 3.])

### 다층 퍼셉트론

In [7]:
def init_network(): # 모든 신경망의 처음 시작세팅
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, .4, .6]])
    network['b1'] = np.array([0.1, .2, .3])
    network['W2'] = np.array([[0.1, 0.4],[0.2,0.5], [0.3,.6]])
    network['b2'] = np.array([0.1, .2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, .4]])
    network['b3'] = np.array([0.1, .2])
    
    return network

def identify_function(x): # 항등
    return x
    
def forward(network, x):
    W1, W2, W3 = network['W1'],network['W2'],network['W3']
    b1, b2, b3 = network['b1'],network['b2'],network['b3']  
    
    a1 = np.dot(x,W1) + b1 # 벡터끼리 내적
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2) + b2# 벡터끼리 내적
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3 # 벡터끼리 내적
    y = identify_function(a3)
    return y

network = init_network()
x = np.array([1., -1.])
y = forward(network, x)
y

array([0.30625898, 0.67286499])

In [8]:
# softmax
def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x-c)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    return y # 클래스가 반환된 확률이 정해져서 나온다