### Python 복습

### Markdown 수식작성
- LaTEX 태그로 작성 가능
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    +
    \begin{pmatrix}
    5 & 5 & 5 \\
    5 & 5 & 5 \\
    \end{pmatrix}
$$
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5 & 5 \\
    5 & 5 \\
    5 & 5 \\
    \end{pmatrix}
$$

### Numpy
    - 데이터는 행렬로 표현(영상도 포함)
    - 선형대수 / 통계 연산을 위한 라이브러리
    
    pandas : 데이터 분석에 가장 많이 활용
    Numpy : 알고리즘 활용에 numpy가 필수적 패키지

In [1]:
# 호출
import numpy as np

### array broadcasting
    - 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
    - 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [3]:
# 초기 가중치 생성
ary = np.array(np.random.randn(10)) # 표준정규분포를 따르는  난수 생성 -> 초기 가중치 생성 때 사용 (n 평균이 0, 표준편차가 1)
ary

array([-1.06461491, -2.26027146,  0.59441921,  1.64770161, -0.45149663,
        0.76198098, -0.06312568, -0.18173559, -1.53625017, -0.66863205])

In [4]:
# 편향값 생성
bias =  np.random.rand(1)
bias

array([0.53288024])

In [6]:
ary + bias # array broadcasting

array([-0.53173467, -1.72739122,  1.12729945,  2.18058184,  0.08138361,
        1.29486122,  0.46975456,  0.35114465, -1.00336993, -0.13575181])

### 통계함수
    - max, min, mean, median, var, std

In [7]:
np.max(ary), np.min(ary) # min-max normalization 때 사용 -> 데이터 정규화

(1.6477016059087821, -2.260271458658668)

### Random 모듈
    - seed : 랜덤 모듈의 규칙값. 난수 생성 환경 고정
    - randint : 균등분포로 정수생성
    - randn : 정규분포로 난수생성
    - shuffle : 무작위 섞기
    - choice : 특정확률로 데이터 뽑기

### seed

In [8]:
seed = 603 # 머신/딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [9]:
r1,r2,r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

### 머신러닝 예시
scaㅣing 처리 후 return 값으로 ndarry 타입 데이터로 출력

In [10]:
from sklearn. preprocessing import MinMaxScaler
import pandas as pd

x = np.random.randint(1,100, 10).reshape(-1,2)  # 5행 2열 데이터 생성
df = pd.DataFrame(x)

df

0   1
0  94  21
1  49  93
2   5  96
3  29  83
4  77  45

In [12]:
scaled_data = MinMaxScaler().fit_transform(df)  # 정규화
scaled_data, type(scaled_data)

(array([[1.        , 0.        ],
        [0.49438202, 0.96      ],
        [0.        , 1.        ],
        [0.26966292, 0.82666667],
        [0.80898876, 0.32      ]]),
 numpy.ndarray)

### Zero 행렬 만들기

In [13]:
zero_ary = np.zeros((4,4))
zero_ary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
seed = 1

np.random.seed(seed)
a = np.random.rand(4)
a

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [ ]:
for i in range(4):
    zero_ary[i][i] = ary[i]

In [ ]:
for i in range(4):
    for j in range(4):
        if i == j:
            zero_ary[i][j] = a[i]
        else:
            continue
zero_ary

In [21]:
import numpy as np
w = np.random.rand(4)
shp = np.zeros((4,4))

for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j: shp[i][j] = w[i]
shp

array([[0.14675589, 0.        , 0.        , 0.        ],
       [0.        , 0.09233859, 0.        , 0.        ],
       [0.        , 0.        , 0.18626021, 0.        ],
       [0.        , 0.        , 0.        , 0.34556073]])

In [22]:
import numpy as np
diag_matrix = np.diag(np.random.rand(4))

diag_matrix

array([[0.39676747, 0.        , 0.        , 0.        ],
       [0.        , 0.53881673, 0.        , 0.        ],
       [0.        , 0.        , 0.41919451, 0.        ],
       [0.        , 0.        , 0.        , 0.6852195 ]])

### Function
    - 반복성을 줄이고 함수로 선언한 연산을 재사용
    - 객체지향 언어의 가장 큰 장점

In [ ]:
'''python
def 함수명(파라미터):
    return 출력값
'''

In [25]:
# 리턴을 선언하지 않고 사용하는 경우 => 함수가 연산 도구로만 사용될 때
# 전역변수, 지역변수
num = 603

def today():
    num = 604
    print(num)

today()
print(num)

604
603


In [26]:
num = 603
print(num)

def today():
    global num
    num = 604
    print(num)

today()
print("*************")
print(num)

603
604
*************
604


### map 함수와 pandas의 apply는 유사한 기능
    - 순서가 있는 데이터 값에 함수를 모두 적용하여 결과를 출력하는 함수

In [ ]:
# map(적용할 함수, 입력할 데이터)

In [29]:
num_txt = "1 2 3 4 5 6"
num_int = list(map(int,num_txt.split(" ")))

num_int

[1, 2, 3, 4, 5, 6]

#### lambda 함수
    - 간단한 연산을 구현하여 일시적으로 사용하는 함수

```python
lambda 리턴: 연산
```

In [32]:
seq = np.random.randint(1,101,10)
q = list(map(lambda x:x//3, seq ))
seq, q

(array([87, 14, 10,  8, 64, 62, 23, 58,  2,  1]),
 [29, 4, 3, 2, 21, 20, 7, 19, 0, 0])