In [31]:
# from sklearn import svm, metrics
# from sklearn.neighbors import KNeighborsClassifier    # 분류
# from sklearn.neighbors import KNeighborsRegressor     # 회귀 - 예측
from sklearn.linear_model import LinearRegression       # 선형회귀
from sklearn.preprocessing import PolynomialFeatures    # 다항특성을 만들어주는 라이브러리
from sklearn.preprocessing import StandardScaler        # 표준화 작업
from sklearn.model_selection import train_test_split    
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import glob, os.path, re
import random

matplotlib.rcParams['axes.unicode_minus'] = False 
matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # : windows 사용자용
matplotlib.rcParams['font.size'] = '10' 

In [32]:
# [ 도미 ]
bream_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 31.5, 32.0, 32.0, 32.0, 33.0, 33.0,
33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0]
bream_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 500.0, 340.0, 600.0, 600.0, 700.0, 700.0,
610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0]

#[ 빙어 ]
smelt_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
smelt_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [ ]:
# 로지스틱 회귀를 적용해서
# 도미, 빙어 test세트의 5개를 분류하고
# 5개를 몇 %의 확률로 선택을 했는지 출력하시오
# train, test 정답률 출력하시오

In [44]:
## 판다스
length = bream_length + smelt_length
weight = bream_weight + smelt_weight
result = ['도미']*35+['빙어']*14

df = pd.DataFrame([length,weight,result])
df = df.T
df.head(2)

target = df[2].to_numpy()
data = df.iloc[:,:-1].to_numpy()

In [ ]:
## numpy
length = np.array(bream_length + smelt_length)
weight = np.array(bream_weight + smelt_weight)
data = np.column_stack(length,weight)
target = np.array(['도미']*35+['빙어']*14)

In [15]:
len(smelt_length)

14

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       49 non-null     float64
 1   1       49 non-null     float64
dtypes: float64(2)
memory usage: 916.0 bytes


In [13]:
df.shape

(49, 2)

In [37]:
# train, test 분리
train_input, test_input, train_target, test_target = train_test_split(df.iloc[:,:2],df.iloc[:,2],random_state=42)

# 표준화
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

## 다른 데이터들도 표준화시켜주어야 함
new = ss.transform([[25,150]])
new2 = ss.transform([[30,600]])
new3 = ss.transform([[6.8,9.7]])

# 훈련시키기
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_scaled, train_target)

# 정답률
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))


1.0
1.0


In [38]:
predict = lr.predict(new)
predict

array([1., 0., 0., 0., 1.])

In [45]:
proba = lr.predict_proba(test_scaled[:5])
proba


array([[0.05911757, 0.94088243],
       [0.88612939, 0.11387061],
       [0.84400618, 0.15599382],
       [0.89014803, 0.10985197],
       [0.01192533, 0.98807467]])

In [46]:
decisions = lr.decision_function(test_scaled[:5])
decisions

array([ 2.76729004, -2.05180021, -1.68834341, -2.09225401,  4.41709346])

In [ ]:
from scipy.special import softmax

proba = softmax(decisions,axis=1)
np.round(proba,decimals=3)